name: java
on: push
env:
  PROXY: proxy.zyte.com:8011
  URL: https://httpbin.scrapinghub.com/ip
  KEY: ${{secrets.KEY}}
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make java-7
      - run: make java-14
